### ISSUE TITLE
andorid上乐谱渲染缓慢的问题解决了么？

### ISSUE THREAD

**Issue by ifredom** [showtan001/react-native-echarts-map#22]
抱歉兄弟，不知道怎么发私信，哈哈。osmd, andorid上乐谱渲染缓慢的问题解决了么？

**Comment by showtan001** [comment]
@ifredom 解决了  老哥   以前用React写的   用原生JS写渲染就没问题了

**Comment by ifredom** [comment]
在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？

**Comment by showtan001** [comment]
> 在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？

3秒知足了，我100多200个小节的曲谱加载和解析各种数据要七八秒

**Comment by ifredom** [comment]
> > 在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？
> 
> 3秒知足了，我100多200个小节的曲谱加载和解析各种数据要七八秒

**Comment by ifredom** [comment]
> > 在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？
> 
> 3秒知足了，我100多200个小节的曲谱加载和解析各种数据要七八秒


d


> > 在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？
> 
> 3秒知足了，我100多200个小节的曲谱加载和解析各种数据要七八秒
哈哈哈，这岂不是得看7-8秒得 loading

**Comment by ifredom** [comment]
> > 在android上通过webview加载比较复杂的曲子，最快都得3秒以上，愣是加快不了速度，后来换成原生了。心头恨啊，你是怎么加载的？
> 
> 3秒知足了，我100多200个小节的曲谱加载和解析各种数据要七八秒


这岂不是得看着loading 七八秒， 哈哈哈
